# Site settings
title: Ravi Ranjan
twitter_username: ravi2519
name: Ravi Ranjan

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/ravi2519
 - title: StackOverflow
   url: https://stackoverflow.com/users/414744/ravi-ranjan
 - title: LinkedIn
   url: https://www.linkedin.com/in/ravi-ranjan-5073b910

#Any buzzword skills you want to include
skills:
 - Java 8
 - Spring MVC
 - Spring Data
 - Spring Boot
 - Hibernate
 - Perl
 - Python
 - SQLite
 - Oracle
 - Javascript
 - jQuery
 - jQuery UI
 - HTML5
 - Flex
 - ActionScript
 - Dojo
 - Typescript
 - FLUX Workflow Engine
 - CSS
 - UML
 - Design Patterns
 - JBOSS
 - Firefly
 - Apache Tomcat 7
 - WebLogic
 - Microservices
 - TDD
 - Agile
 - qunit
 - jUnit/Mockito
 - Bootstrap
 - Angular 7
 - Maven
 - Gradle
 - Ant
 - Git
 - TFS
 - CVS
 - Linux
 - Ubuntu
 - FreeBSD
 - VIM
 - tmux
 - IntelliJ Idea
 - Eclipse
 - Visual Code

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Programmer Analyst Senior
   start: 2016
   end: Ongoing
   employer: Fidelity Information Services Pvt Ltd, India
   description: 
 - title: Programmer Analyst II
   start: 2015
   end: 2016
   employer: Fidelity Information Services Pvt Ltd, India
   description: 
 - title: Programmer Analyst I
   start: 2013
   end: 2015
   employer: Fidelity Information Services Pvt Ltd, India
   description: 
 - title: Technical Analyst
   start: 2012
   end: 2013
   employer: Infosys
   description: 
 - title: Senior Software Engineer 
   start: 2011
   end: 2012
   employer: Infosys
   description: 
 - title: Software Engineer 
   start: 2019
   end: 2011
   employer: Infosys
   description: 
   
#Education is required
education:
 - level: Bachelor of Engineering
   date: 2008
   subject: Electronics and Communication
   university: Rajiv Gandhi Prodyogiki Vishwavidyalaya

#This section is optional (as is the image link below)
aiclass:
   profileurl: https://drive.google.com/file/d/1-CwB1lYj4qQE2bVvRyYdoN6fYnh0XH68/view?usp=drivesdk&usp=embed_facebook
   courses:
    - title: Statement of Accomplishment by Sebastian Thrun and Peter Norvig for "Introduction to Artificial Intelligence"
      link: https://drive.google.com/file/d/1-CwB1lYj4qQE2bVvRyYdoN6fYnh0XH68/view?usp=drivesdk&usp=embed_facebook
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: December 21, 2011

coursera:
   profileurl: https://www.coursera.org/user/8eb7526d9f113d13935e1c3584835efe
   courses:
    - title: The Arduino Platform and C Programming
      link: https://www.coursera.org/learn/arduino-platform
      date: 2011

#List of interesting Github repo/projects to include - optional
github:
 - ravi2519/ds_algo
 - ravi2519/lane-detection
 - ravi2519/opencvpy
 - ravi2519/SpringBoot-REST-Api

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/414744/ravi-ranjan
   flairimageurl: https://stackoverflow.com/users/flair/414744.png
   
intro: |
  I am a Full Stack Java Developer with 11 years of working experience in FinTech domain. I have worked with Java 8, JEE, Spring Boot, Spring MVC, Spring Core, JPA, Hibernate, SQLite, Oracle, MS SQL, etc on the Backend and JavaScript, Flex, jQuery, Angular, Typescript, CSS, etc on the Frontend. Additionally I have beginners knowledge in Machine Learning and OpenCV. I am equally experienced with writing Perl and Python scripts and tools. I have experience in developing REST APIs, Single Page Applications and MicroServices.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
#additionalinfo: |
#   <strong>Scala</strong>: My current role uses Scala as the primary language and have been building applications in Scala for the last two years. I am familiar with a range of Scala libraries, such as <a target="_blank" href="https://automateddeveloper.blogspot.com/2017/12/an-opinionated-guide-to-building-apis.html"> Akka-Http for building microservices</a> and <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/09/generic-programming-with-scala.html"> Shapeless for generic programming</a>, as well as familiar with a range of <a target="_blank" href="https://basementcrowd.com/2018/11/28/scala-the-aux-pattern-path-dependent-types/" >functional programming techniques available</a>.<br/><br/>
#   <strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks. I have worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others. <br/><br/>
#   <strong>Groovy</strong> I have used Groovy as a language in production for ~4 years and I am familiar with many of the languages features (such as writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>) and quirks (such as <a target="_blank" href="https://dzone.com/articles/groovy-retrospective-an-addendum-memory-usage-perm">memory leak issues</a>). <br/><br/>
#   <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito, <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/05/serverless-with-aws-lambda-scala.html">Lambda</a> and its more recent <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/10/machine-learning-with-aws-scala.html">Machine Learning capabilities</a>.<br/><br/>
#   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS, Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
#   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
#   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>
#   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="https://projects.spring.io/spring-social/">https://projects.spring.io/spring-social/</a>. <br/><br/>
#   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="https://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
